const primaryInvestigation = {
    caseId: "TKT-2026-00125",
    summary: {
        significantEventCount: 5,
        relationshipCount: 10,
    },
    timeline: [
        {
            id: "EVT-001",
            timestamp: "2026-07-19T17:31:14",
            title: "Malicious executable launched",
            summary:
                "mssecsvc.exe was launched on MSS-ECSVC from a user-writable directory.",
            description:
                "Endpoint telemetry shows mssecsvc.exe launching from a user-writable directory on MSS-ECSVC under the svc-mssql session. The executable hash matches a confirmed WannaCry payload.",
            source: "NetWitness Endpoint",
            category: "Execution",
            severity: "Critical",
            significance: "Critical execution event",
            entityIds: ["ENT-ENDPOINT-001", "ENT-PROCESS-001", "ENT-USER-001"],
            entityTypes: ["Endpoint", "Process", "User"],
            techniqueIds: ["T1082"],
            tactic: "Discovery",
            evidenceIds: ["EVD-001", "EVD-002"],
            raw: "process.start image=mssecsvc.exe host=MSS-ECSVC user=svc-mssql path=C:\\Users\\Public\\mssecsvc.exe",
        },
        {
            id: "EVT-002",
            timestamp: "2026-07-19T17:32:08",
            title: "Encoded PowerShell command executed",
            summary: "mssecsvc.exe spawned PowerShell with an encoded command.",
            description:
                "The WannaCry process spawned powershell.exe with an encoded command that attempted to collect host information and prepare network communication.",
            source: "NetWitness Endpoint",
            category: "Execution",
            severity: "High",
            significance: "Suspicious command execution",
            entityIds: [
                "ENT-PROCESS-001",
                "ENT-PROCESS-002",
                "ENT-ENDPOINT-001",
            ],
            entityTypes: ["Process", "Endpoint"],
            techniqueIds: ["T1059.001"],
            tactic: "Execution",
            evidenceIds: ["EVD-003", "EVD-004"],
            raw: "powershell.exe -NoProfile -EncodedCommand JABXAG...",
        },
        {
            id: "EVT-003",
            timestamp: "2026-07-19T17:33:27",
            title: "Connection established with a known malicious IP",
            summary: "MSS-ECSVC connected to 185.159.82.47 over HTTP.",
            description:
                "Network telemetry recorded an outbound HTTP connection from MSS-ECSVC to infrastructure associated with WannaCry command-and-control activity.",
            source: "NetWitness Network",
            category: "Network",
            severity: "Critical",
            significance: "Confirmed command-and-control",
            entityIds: ["ENT-ENDPOINT-001", "ENT-IP-001"],
            entityTypes: ["Endpoint", "IP Address"],
            techniqueIds: ["T1071.001"],
            tactic: "Command and Control",
            evidenceIds: ["EVD-005", "EVD-006", "EVD-007"],
            raw: "src=MSS-ECSVC dst=185.159.82.47 dst_port=80 action=allowed",
        },
        {
            id: "EVT-004",
            timestamp: "2026-07-19T17:34:11",
            title: "WannaCry kill-switch domain queried",
            summary: "The endpoint queried the WannaCry kill-switch domain.",
            description:
                "DNS telemetry shows MSS-ECSVC querying the domain used by WannaCry to determine whether execution should continue.",
            source: "NetWitness Network",
            category: "Network",
            severity: "High",
            significance: "Malware family corroboration",
            entityIds: ["ENT-ENDPOINT-001", "ENT-DOMAIN-001"],
            entityTypes: ["Endpoint", "Domain"],
            techniqueIds: ["T1071.001"],
            tactic: "Command and Control",
            evidenceIds: ["EVD-008", "EVD-009"],
            raw: "query=iuqerfsodp9ifjaposdfjhgosurijfaewrwergwea.com response=NXDOMAIN",
        },
        {
            id: "EVT-005",
            timestamp: "2026-07-19T17:36:42",
            title: "Threat intelligence confirmed malicious indicators",
            summary:
                "Three providers associated the observed indicators with WannaCry.",
            description:
                "VirusTotal, AlienVault OTX and AbuseIPDB returned consistent malicious or suspicious verdicts for the file hash, IP address and domain.",
            source: "Aegis Threat Intelligence Agent",
            category: "Threat Intelligence",
            severity: "High",
            significance: "High-confidence enrichment",
            entityIds: [
                "ENT-HASH-001",
                "ENT-IP-001",
                "ENT-DOMAIN-001",
                "ENT-TI-001",
            ],
            entityTypes: ["File Hash", "IP Address", "Domain", "Provider"],
            techniqueIds: [],
            tactic: "",
            evidenceIds: ["EVD-010", "EVD-011", "EVD-012"],
            raw: "providers=VirusTotal,AlienVault OTX,AbuseIPDB agreement=3/3",
        },
    ],
    mitreAttack: [
        {
            id: "MITRE-001",
            tactic: "Execution",
            techniqueId: "T1059.001",
            techniqueName: "PowerShell",
            confidence: "High",
            confidenceScore: 94,
            evidenceSummary:
                "Encoded PowerShell execution was detected on MSS-ECSVC.",
            evidenceIds: ["EVD-003", "EVD-004"],
            timelineEventIds: ["EVT-002"],
            entityIds: ["ENT-PROCESS-002", "ENT-ENDPOINT-001"],
            source: "Aegis Investigation Agent",
            validationStatus: "Unreviewed",
        },
        {
            id: "MITRE-002",
            tactic: "Command and Control",
            techniqueId: "T1071.001",
            techniqueName: "Web Protocols",
            confidence: "High",
            confidenceScore: 95,
            evidenceSummary:
                "Outbound HTTP traffic reached known malicious infrastructure.",
            evidenceIds: ["EVD-005", "EVD-006", "EVD-007", "EVD-008"],
            timelineEventIds: ["EVT-003", "EVT-004"],
            entityIds: ["ENT-ENDPOINT-001", "ENT-IP-001", "ENT-DOMAIN-001"],
            source: "Aegis Investigation Agent",
            validationStatus: "Unreviewed",
        },
        {
            id: "MITRE-003",
            tactic: "Discovery",
            techniqueId: "T1082",
            techniqueName: "System Information Discovery",
            confidence: "Medium",
            confidenceScore: 78,
            evidenceSummary:
                "The encoded command requested local host and operating-system details.",
            evidenceIds: ["EVD-002", "EVD-003"],
            timelineEventIds: ["EVT-001", "EVT-002"],
            entityIds: ["ENT-ENDPOINT-001", "ENT-PROCESS-002"],
            source: "Aegis Investigation Agent",
            validationStatus: "Unreviewed",
        },
    ],
    entities: [
        {
            id: "ENT-ENDPOINT-001",
            type: "Endpoint",
            label: "MSS-ECSVC",
            value: "MSS-ECSVC",
            riskLevel: "Critical",
            firstSeen: "2026-07-19T17:31:14",
            lastSeen: "2026-07-19T17:36:42",
            evidenceIds: ["EVD-001", "EVD-005", "EVD-008"],
            timelineEventIds: ["EVT-001", "EVT-002", "EVT-003", "EVT-004"],
            techniqueIds: ["T1059.001", "T1071.001", "T1082"],
            source: "NetWitness",
            relatedCaseIds: [],
        },
        {
            id: "ENT-USER-001",
            type: "User",
            label: "svc-mssql",
            value: "svc-mssql",
            riskLevel: "Medium",
            firstSeen: "2026-07-19T17:31:14",
            lastSeen: "2026-07-19T17:32:08",
            evidenceIds: ["EVD-001"],
            timelineEventIds: ["EVT-001"],
            techniqueIds: [],
            source: "NetWitness Endpoint",
            relatedCaseIds: [],
        },
        {
            id: "ENT-PROCESS-001",
            type: "Process",
            label: "mssecsvc.exe",
            value: "C:\\Users\\Public\\mssecsvc.exe",
            riskLevel: "Critical",
            firstSeen: "2026-07-19T17:31:14",
            lastSeen: "2026-07-19T17:33:27",
            evidenceIds: ["EVD-001", "EVD-002", "EVD-003"],
            timelineEventIds: ["EVT-001", "EVT-002"],
            techniqueIds: ["T1082"],
            source: "NetWitness Endpoint",
            relatedCaseIds: [],
        },
        {
            id: "ENT-PROCESS-002",
            type: "Process",
            label: "powershell.exe",
            value: "powershell.exe",
            riskLevel: "High",
            firstSeen: "2026-07-19T17:32:08",
            lastSeen: "2026-07-19T17:32:08",
            evidenceIds: ["EVD-003", "EVD-004"],
            timelineEventIds: ["EVT-002"],
            techniqueIds: ["T1059.001", "T1082"],
            source: "NetWitness Endpoint",
            relatedCaseIds: [],
        },
        {
            id: "ENT-HASH-001",
            type: "File Hash",
            label: "a4f8…91c2",
            value: "a4f8c764d3a6b54f6d9be91c2",
            riskLevel: "Critical",
            firstSeen: "2026-07-19T17:31:14",
            lastSeen: "2026-07-19T17:36:42",
            evidenceIds: ["EVD-002", "EVD-010"],
            timelineEventIds: ["EVT-001", "EVT-005"],
            techniqueIds: [],
            source: "VirusTotal",
            relatedCaseIds: [],
        },
        {
            id: "ENT-IP-001",
            type: "IP Address",
            label: "185.159.82.47",
            value: "185.159.82.47",
            riskLevel: "Critical",
            firstSeen: "2026-07-19T17:33:27",
            lastSeen: "2026-07-19T17:36:42",
            evidenceIds: ["EVD-005", "EVD-006", "EVD-011"],
            timelineEventIds: ["EVT-003", "EVT-005"],
            techniqueIds: ["T1071.001"],
            source: "AbuseIPDB",
            relatedCaseIds: [],
        },
        {
            id: "ENT-DOMAIN-001",
            type: "Domain",
            label: "iuqerfsodp9…com",
            value: "iuqerfsodp9ifjaposdfjhgosurijfaewrwergwea.com",
            riskLevel: "High",
            firstSeen: "2026-07-19T17:34:11",
            lastSeen: "2026-07-19T17:36:42",
            evidenceIds: ["EVD-008", "EVD-009", "EVD-012"],
            timelineEventIds: ["EVT-004", "EVT-005"],
            techniqueIds: ["T1071.001"],
            source: "AlienVault OTX",
            relatedCaseIds: [],
        },
        {
            id: "ENT-TI-001",
            type: "Provider",
            label: "Threat Intel Providers",
            value: "VirusTotal · OTX · AbuseIPDB",
            riskLevel: "Low",
            firstSeen: "2026-07-19T17:36:42",
            lastSeen: "2026-07-19T17:36:42",
            evidenceIds: ["EVD-010", "EVD-011", "EVD-012"],
            timelineEventIds: ["EVT-005"],
            techniqueIds: [],
            source: "Aegis",
            relatedCaseIds: [],
        },
    ],
    relationships: [
        {
            id: "REL-001",
            sourceEntityId: "ENT-USER-001",
            targetEntityId: "ENT-ENDPOINT-001",
            type: "Logged into",
            timestamp: "2026-07-19T17:31:14",
            evidenceIds: ["EVD-001"],
            timelineEventIds: ["EVT-001"],
        },
        {
            id: "REL-002",
            sourceEntityId: "ENT-ENDPOINT-001",
            targetEntityId: "ENT-PROCESS-001",
            type: "Executed",
            timestamp: "2026-07-19T17:31:14",
            evidenceIds: ["EVD-001"],
            timelineEventIds: ["EVT-001"],
        },
        {
            id: "REL-003",
            sourceEntityId: "ENT-PROCESS-001",
            targetEntityId: "ENT-PROCESS-002",
            type: "Spawned",
            timestamp: "2026-07-19T17:32:08",
            evidenceIds: ["EVD-003"],
            timelineEventIds: ["EVT-002"],
        },
        {
            id: "REL-004",
            sourceEntityId: "ENT-PROCESS-001",
            targetEntityId: "ENT-HASH-001",
            type: "Has hash",
            timestamp: "2026-07-19T17:31:14",
            evidenceIds: ["EVD-002"],
            timelineEventIds: ["EVT-001"],
        },
        {
            id: "REL-005",
            sourceEntityId: "ENT-ENDPOINT-001",
            targetEntityId: "ENT-IP-001",
            type: "Connected to",
            timestamp: "2026-07-19T17:33:27",
            evidenceIds: ["EVD-005"],
            timelineEventIds: ["EVT-003"],
        },
        {
            id: "REL-006",
            sourceEntityId: "ENT-ENDPOINT-001",
            targetEntityId: "ENT-DOMAIN-001",
            type: "Queried",
            timestamp: "2026-07-19T17:34:11",
            evidenceIds: ["EVD-008"],
            timelineEventIds: ["EVT-004"],
        },
        {
            id: "REL-007",
            sourceEntityId: "ENT-TI-001",
            targetEntityId: "ENT-HASH-001",
            type: "Reported by",
            timestamp: "2026-07-19T17:36:42",
            evidenceIds: ["EVD-010"],
            timelineEventIds: ["EVT-005"],
        },
        {
            id: "REL-008",
            sourceEntityId: "ENT-TI-001",
            targetEntityId: "ENT-IP-001",
            type: "Reported by",
            timestamp: "2026-07-19T17:36:42",
            evidenceIds: ["EVD-011"],
            timelineEventIds: ["EVT-005"],
        },
        {
            id: "REL-009",
            sourceEntityId: "ENT-TI-001",
            targetEntityId: "ENT-DOMAIN-001",
            type: "Reported by",
            timestamp: "2026-07-19T17:36:42",
            evidenceIds: ["EVD-012"],
            timelineEventIds: ["EVT-005"],
        },
        {
            id: "REL-010",
            sourceEntityId: "ENT-PROCESS-002",
            targetEntityId: "ENT-ENDPOINT-001",
            type: "Detected on",
            timestamp: "2026-07-19T17:32:08",
            evidenceIds: ["EVD-004"],
            timelineEventIds: ["EVT-002"],
        },
    ],
    evidence: [
        [
            "EVD-001",
            "Process event",
            "mssecsvc.exe launched on MSS-ECSVC",
            "NetWitness Endpoint",
            "17:31:14",
            "High",
            "Validated",
            ["ENT-ENDPOINT-001", "ENT-PROCESS-001", "ENT-USER-001"],
            "EVT-001",
            "MITRE-003",
        ],
        [
            "EVD-002",
            "File hash",
            "a4f8c764…be91c2",
            "NetWitness Endpoint",
            "17:31:16",
            "High",
            "Validated",
            ["ENT-PROCESS-001", "ENT-HASH-001"],
            "EVT-001",
            "MITRE-003",
        ],
        [
            "EVD-003",
            "Command",
            "Encoded PowerShell command",
            "NetWitness Endpoint",
            "17:32:08",
            "High",
            "Validated",
            ["ENT-PROCESS-001", "ENT-PROCESS-002"],
            "EVT-002",
            "MITRE-001",
        ],
        [
            "EVD-004",
            "Process tree",
            "mssecsvc.exe → powershell.exe",
            "NetWitness Endpoint",
            "17:32:08",
            "High",
            "Validated",
            ["ENT-ENDPOINT-001", "ENT-PROCESS-002"],
            "EVT-002",
            "MITRE-001",
        ],
        [
            "EVD-005",
            "Network connection",
            "MSS-ECSVC → 185.159.82.47:80",
            "NetWitness Network",
            "17:33:27",
            "High",
            "Validated",
            ["ENT-ENDPOINT-001", "ENT-IP-001"],
            "EVT-003",
            "MITRE-002",
        ],
        [
            "EVD-006",
            "IP reputation",
            "185.159.82.47 — malicious",
            "AbuseIPDB",
            "17:33:30",
            "High",
            "Validated",
            ["ENT-IP-001"],
            "EVT-003",
            "MITRE-002",
        ],
        [
            "EVD-007",
            "Network log",
            "HTTP session metadata",
            "NetWitness Network",
            "17:33:31",
            "High",
            "Validated",
            ["ENT-ENDPOINT-001", "ENT-IP-001"],
            "EVT-003",
            "MITRE-002",
        ],
        [
            "EVD-008",
            "DNS query",
            "WannaCry kill-switch domain queried",
            "NetWitness Network",
            "17:34:11",
            "High",
            "Validated",
            ["ENT-ENDPOINT-001", "ENT-DOMAIN-001"],
            "EVT-004",
            "MITRE-002",
        ],
        [
            "EVD-009",
            "Domain record",
            "Kill-switch domain returned NXDOMAIN",
            "NetWitness Network",
            "17:34:12",
            "Medium",
            "Validated",
            ["ENT-DOMAIN-001"],
            "EVT-004",
            "MITRE-002",
        ],
        [
            "EVD-010",
            "Threat intelligence",
            "File hash detected by 66 vendors",
            "VirusTotal",
            "17:36:40",
            "High",
            "Validated",
            ["ENT-HASH-001", "ENT-TI-001"],
            "EVT-005",
            "",
        ],
        [
            "EVD-011",
            "Threat intelligence",
            "IP matched 50 OTX pulses",
            "AlienVault OTX",
            "17:36:41",
            "High",
            "Validated",
            ["ENT-IP-001", "ENT-TI-001"],
            "EVT-005",
            "MITRE-002",
        ],
        [
            "EVD-012",
            "Threat intelligence",
            "Domain associated with WannaCry",
            "AlienVault OTX",
            "17:36:42",
            "High",
            "Validated",
            ["ENT-DOMAIN-001", "ENT-TI-001"],
            "EVT-005",
            "MITRE-002",
        ],
    ].map(
        ([
            id,
            type,
            title,
            source,
            collectedAt,
            confidence,
            validationStatus,
            entityIds,
            timelineEventId,
            mitreMappingId,
        ]) => ({
            id,
            type,
            title,
            source,
            collectedAt,
            confidence,
            validationStatus,
            entityIds,
            timelineEventId,
            mitreMappingId,
        }),
    ),
    activity: [
        {
            id: "ACT-001",
            time: "05:41 PM",
            title: "Investigation Agent completed",
            description: "Likely true-positive verdict recorded.",
        },
        {
            id: "ACT-002",
            time: "05:36 PM",
            title: "Threat intelligence output received",
            description: "Three provider responses attached to the case.",
        },
        {
            id: "ACT-003",
            time: "05:30 PM",
            title: "Analyst opened the case",
            description: "Soong Yang reviewed the agent summary.",
        },
        {
            id: "ACT-004",
            time: "05:28 PM",
            title: "Investigation Agent started",
            description: "Endpoint and network evidence collection began.",
        },
    ],
};

const emptyInvestigation = {
    summary: { significantEventCount: 0, relationshipCount: 0 },
    timeline: [],
    mitreAttack: [],
    entities: [],
    relationships: [],
    evidence: [],
    activity: [],
};

export function getInvestigationCaseData(caseId) {
    if (caseId === primaryInvestigation.caseId) {
        return primaryInvestigation;
    }

    return { ...emptyInvestigation, caseId };
}
