import { applicationState } from "./state.js";
import { escapeHtml } from "./utils.js";

let currentData = null;
let currentActions = null;

function mappingStatus(mapping) {
    return (
        applicationState.investigation.validationStatuses[mapping.id] ??
        mapping.validationStatus
    );
}

function renderTechniqueCard(mapping) {
    const selected =
        mapping.id === applicationState.investigation.selectedMitreMappingId;
    return `
        <article class="mitre-card ${selected ? "is-selected" : ""}" data-mitre-card="${mapping.id}">
            <button class="mitre-card__summary" type="button" aria-expanded="${selected}">
                <span class="mitre-card__tactic">${escapeHtml(mapping.tactic)}</span>
                <span class="mitre-card__identity"><strong>${escapeHtml(mapping.techniqueId)}</strong><span>${escapeHtml(mapping.techniqueName)}</span></span>
                <span class="stage-status ${mapping.confidence === "High" ? "good" : "warn"}">${escapeHtml(mapping.confidence)} · ${mapping.confidenceScore}%</span>
                <span class="mitre-validation-status">${escapeHtml(mappingStatus(mapping))}</span>
                <span aria-hidden="true">${selected ? "−" : "+"}</span>
            </button>
            ${
                selected
                    ? `<div class="mitre-card__details">
                        <p>${escapeHtml(mapping.evidenceSummary)}</p>
                        <dl class="investigation-detail-list">
                            <div><dt>Supporting evidence</dt><dd>${mapping.evidenceIds.length} items</dd></div>
                            <div><dt>Evidence source</dt><dd>${escapeHtml(mapping.source)}</dd></div>
                            <div><dt>Timeline events</dt><dd>${mapping.timelineEventIds.length}</dd></div>
                            <div><dt>Related entities</dt><dd>${mapping.entityIds.length}</dd></div>
                            <div><dt>Generated by</dt><dd>Aegis Investigation Agent</dd></div>
                        </dl>
                        <div class="mitre-validation-controls" aria-label="Analyst validation">
                            <button type="button" data-mitre-validation="Confirmed">Confirm Mapping</button>
                            <button type="button" data-mitre-validation="Incorrect">Mark as Incorrect</button>
                            <button type="button" data-mitre-validation="Needs More Evidence">Needs More Evidence</button>
                        </div>
                        <div class="investigation-action-row">
                            <button type="button" data-mitre-action="evidence">View Supporting Evidence</button>
                            <button type="button" data-mitre-action="timeline">View Timeline Event</button>
                            <button type="button" data-mitre-action="entities">View Related Entities</button>
                        </div>
                    </div>`
                    : ""
            }
        </article>`;
}

function renderMitreContent(container) {
    const selectedTactic = applicationState.investigation.mitreTactic;
    const tactics = [
        ...new Set(currentData.mitreAttack.map((item) => item.tactic)),
    ];
    const mappings = currentData.mitreAttack.filter(
        (item) => selectedTactic === "all" || item.tactic === selectedTactic,
    );
    container.innerHTML = `
        <section class="section investigation-panel">
            <div class="investigation-panel__head">
                <div><h3>MITRE ATT&amp;CK Mappings</h3><p>Evidence-backed tactics and techniques for this case</p></div>
                <span class="stage-status">${mappings.length} mapped</span>
            </div>
            <div class="mitre-tactics" aria-label="Filter by MITRE tactic">
                <button type="button" data-mitre-tactic="all" class="${selectedTactic === "all" ? "active" : ""}">All Tactics</button>
                ${tactics.map((tactic) => `<button type="button" data-mitre-tactic="${escapeHtml(tactic)}" class="${selectedTactic === tactic ? "active" : ""}">${escapeHtml(tactic)} <span>${currentData.mitreAttack.filter((mapping) => mapping.tactic === tactic).length}</span></button>`).join('<span class="mitre-tactic-arrow" aria-hidden="true">→</span>')}
            </div>
            <div class="mitre-card-list">
                ${mappings.length ? mappings.map(renderTechniqueCard).join("") : '<div class="investigation-empty">No evidence-backed MITRE ATT&amp;CK techniques have been mapped yet.</div>'}
            </div>
        </section>`;
}

function handleMitreClick(event, container) {
    const tactic = event.target.closest("[data-mitre-tactic]");
    if (tactic) {
        applicationState.investigation.mitreTactic = tactic.dataset.mitreTactic;
        renderMitreContent(container);
        return;
    }
    const card = event.target.closest("[data-mitre-card]");
    if (!card) return;
    const mapping = currentData.mitreAttack.find(
        (item) => item.id === card.dataset.mitreCard,
    );
    const validation = event.target.closest("[data-mitre-validation]");
    if (validation) {
        applicationState.investigation.validationStatuses[mapping.id] =
            validation.dataset.mitreValidation;
        currentActions.activity(
            `MITRE ATT&CK mapping ${validation.dataset.mitreValidation.toLowerCase()}`,
            `${mapping.techniqueId} · ${mapping.techniqueName}`,
        );
        renderMitreContent(container);
        return;
    }
    const action = event.target.closest("[data-mitre-action]");
    if (action) {
        currentActions.navigate(action.dataset.mitreAction, {
            evidenceId: mapping.evidenceIds[0],
            eventId: mapping.timelineEventIds[0],
            entityId: mapping.entityIds[0],
            mappingId: mapping.id,
        });
        return;
    }
    applicationState.investigation.selectedMitreMappingId =
        applicationState.investigation.selectedMitreMappingId === mapping.id
            ? null
            : mapping.id;
    currentActions.selectionChanged(
        "mitre",
        `${mapping.techniqueId} ${mapping.techniqueName}`,
    );
    renderMitreContent(container);
}

export function renderMitreAttack(container, data, actions) {
    currentData = data;
    currentActions = actions;
    if (!container.dataset.mitreInitialised) {
        container.addEventListener("click", (event) =>
            handleMitreClick(event, container),
        );
        container.dataset.mitreInitialised = "true";
    }
    renderMitreContent(container);
}

export function highlightMitreTechnique(techniqueId) {
    const mapping = currentData?.mitreAttack.find(
        (item) => item.techniqueId === techniqueId || item.id === techniqueId,
    );
    applicationState.investigation.selectedMitreMappingId = mapping?.id ?? null;
    applicationState.investigation.mitreTactic = mapping?.tactic ?? "all";
}
