source_detection:
  - key: "authentication_details"
    source_type: "Authentication"
  - key: "log_indicators"
    source_type: "LogIndicators"
  - key: "network_indicators"
    source_type: "Network"

mappings:
  Authentication:
    username:
      - "authentication_details.attempted_target_user"
    hostname:
      - "log_indicators.computer_name"
    timestamp:
      - "incident_details.timestamp"
  LogIndicators:
    username:
      - "log_indicators.target_user"
    hostname:
      - "log_indicators.computer_name"
    timestamp:
      - "incident_details.timestamp"
  Network:
    username:
      - "log_indicators.target_user"
    hostname:
      - "log_indicators.computer_name"
      - "network_indicators.source_host"
    timestamp:
      - "incident_details.timestamp"
  Default:
    username:
      - "log_indicators.target_user"
      - "authentication_details.attempted_target_user"
    hostname:
      - "log_indicators.computer_name"
    timestamp:
      - "incident_details.timestamp"
